// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config"
import { defineConfig } from "prisma/config"

import { getPgConnectionString } from "./lib/database-url"

function resolveDatabaseUrl(): string | undefined {
  const raw = process.env.DATABASE_URL
  if (!raw?.trim()) {
    return undefined
  }

  try {
    return getPgConnectionString(raw)
  } catch (error) {
    const message =
      error instanceof Error ? error.message : "Invalid DATABASE_URL"
    throw new Error(`Prisma config: ${message}`)
  }
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: resolveDatabaseUrl(),
  },
})
